### PR TITLE
Correct Indentation for main.c

### PR DESCRIPTION
**Pull request by Voodoobrew101**
This is a basic file clean up to main.c, it could be applied to a few of the files.
The process was automated with STM32CubeIDE > Source > Correct Indentation Command.
Build was successful after formatting as nothing was really changed except that many spaces were replaced with tab indents.
I think it makes the code much easier to read.

### CODE REVIEW

**Comment by Voodoobrew101** [comment]
There were quite a few places where the indentation with spaces was missing or 2 spaces were used instead of 4.
I think @DusKing1  wanted to use 4 spaces instead, but that wasn't in the automated options, and nobody has taken the time to do the cleanup to 4 spaces.
I am looking to find a way to possibly convert the tabs back to 4 spaces.

**Comment by Voodoobrew101** [comment]
here is main.c with indentions fixed but with 4 spaces instead of Indentions
https://github.com/AlkaMotors/AM32-MultiRotor-ESC-firmware/compare/master...Voodoobrew101:patch-6

**Comment by Voodoobrew101** [comment]
Once a decision is made for 4 spaces vs tab indents, other files should be processed. 
Some files such as targets.h might only look correct if spaces are used.

**Review by DusKing1 — COMMENTED** [review]
That's basically up to the maintainer, in this case this should up to @AlkaMotors . Personally I prefer 4 for tab since I write python more often than languages. but if 8 for tabs make sense for you that'll be fine.

**Comment by Voodoobrew101** [comment]
I use the chrome addon [stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne) and the [github-better-sized-tabs-in-code](https://userstyles.org/styles/70979/github-better-sized-tabs-in-code) theme for it which converts the tab indents to 4. Because GitHub doesn't as far as I know always let you view tabs as 4

**Pull request closed without merging**
